### ISSUE TITLE
多个入参如何使用

### ISSUE THREAD

**Issue by wenbinwumei** [twelvet-projects/netty-websocket-spring-boot-starter#8]
`@BeforeHandshake
    public void handshake(NettySession nettySession, HttpHeaders headers, @RequestParam String req, @RequestParam MultiValueMap reqMap, @PathVariable String arg, @PathVariable Map pathMap) {
        nettySession.setSubprotocols("stomp");
        if (!"ok".equals(req)) {
            System.out.println("Authentication failed!");
            // nettySession.close();
        }
        System.out.println(arg);
//        onlineSessionMap.put()
    }

    @OnOpen
    public void onOpen(NettySession nettySession, HttpHeaders headers, @RequestParam String req, @RequestParam MultiValueMap reqMap, @PathVariable String arg, @PathVariable Map pathMap) {
        System.out.println("new connection");
        System.out.println(req);
    }`

这两个方法中@RequestParam String req 和 @PathVariable String arg 在什么情况下能收到值，我测试无论单个参数 还是多个参数都没有值

**Comment by twelvet-s** [comment]
> `@BeforeHandshake public void handshake(NettySession nettySession, HttpHeaders headers, @RequestParam String req, @RequestParam MultiValueMap reqMap, @PathVariable String arg, @PathVariable Map pathMap) { nettySession.setSubprotocols("stomp"); if (!"ok".equals(req)) { System.out.println("Authentication failed!"); // nettySession.close(); } System.out.println(arg); // onlineSessionMap.put() }
> 
> ```
> @OnOpen
> public void onOpen(NettySession nettySession, HttpHeaders headers, @RequestParam String req, @RequestParam MultiValueMap reqMap, @PathVariable String arg, @PathVariable Map pathMap) {
>     System.out.println("new connection");
>     System.out.println(req);
> }`
> ```
> 
> 这两个方法中@RequestParam String req 和 @PathVariable String arg 在什么情况下能收到值，我测试无论单个参数 还是多个参数都没有值

使用方式跟Spring Boot一样的，且经过测试没有问题，无论单还是多
ws://127.0.0.1/ws?req=hello world&req2=hello world
![1714209445014](https://github.com/twelvet-projects/netty-websocket-spring-boot-starter/assets/31510505/e269fbe5-0fcd-41fc-91bd-6cc985653ded)

**Comment by wenbinwumei** [comment]
你说的没错 req和reqMap都有值，我想问的是后面的两个参数 @PathVariable String arg, @PathVariable Map pathMap，ws请求如何传参能给后面两个赋值

**Comment by twelvet-s** [comment]
> 你说的没错 req和reqMap都有值，我想问的是后面的两个参数 @PathVariable String arg, @PathVariable Map pathMap，ws请求如何传参能给后面两个赋值

也是一样的，springboot的使用方式/ws/{arg}，就可以拿到路径参数了

**Comment by wenbinwumei** [comment]
好的 非常感谢

**Comment by miaomiaojianglove** [comment]
> ws://127.0.0.1/ws?req=hello world&req2=hello world

请问下老哥 ws://127.0.0.1/ws?req=hello world&req2=hello world 我以这种方式 为何reqMap内没有内容呢

**Comment by miaomiaojianglove** [comment]
> ws://127.0.0.1/ws?req=hello world&req2=hello world

请问下老哥 ws://127.0.0.1/ws?req=hello world&req2=hello world 我以这种方式 为何reqMap内没有内容呢

**Comment by twelvet-s** [comment]
> > ws://127.0.0.1/ws?req=hello world&req2=hello world
> 
> 请问下老哥 ws://127.0.0.1/ws?req=hello world&req2=hello world 我以这种方式 为何reqMap内没有内容呢

直接使用readme例子进行测试

**Comment by miaomiaojianglove** [comment]
> > > ws://127.0.0.1/ws?req=hello world&req2=hello world
> > 
> > 
> > 请问下老哥 ws://127.0.0.1/ws?req=hello world&req2=hello world 我以这种方式 为何reqMap内没有内容呢
> 
> 直接使用readme例子进行测试

老哥我用的就是readme 
![image](https://github.com/twelvet-projects/netty-websocket-spring-boot-starter/assets/28811199/274e56e0-6745-4051-a276-ce97336e401d)
![image](https://github.com/twelvet-projects/netty-websocket-spring-boot-starter/assets/28811199/62d58cb0-862c-480c-b523-e64e7a0a3ffb)
测试连接
![image](https://github.com/twelvet-projects/netty-websocket-spring-boot-starter/assets/28811199/77426dff-112b-4573-82be-e6842fc1f237)

**Comment by miaomiaojianglove** [comment]
![image](https://github.com/twelvet-projects/netty-websocket-spring-boot-starter/assets/28811199/413c33de-cee6-4867-94e2-4012214c5b31)
我拿掉tableCode 也没有内容
