### ISSUE TITLE
老哥能封装消息发送模块吗

### ISSUE THREAD

**Issue by miaomiaojianglove** [twelvet-projects/netty-websocket-spring-boot-starter#9]
老哥能封装消息发送模块吗

**Comment by twelvet-s** [comment]
> 老哥能封装消息发送模块吗

这是一个基础框架，封装消息发送是什么意思

**Comment by miaomiaojianglove** [comment]
就是现在目前不是只能收消息吗 比如我想给某个session发消息 或者给所有session广播怎么处理呢
原作者说要全部循环所有session才能发 但代码里面没有看到对应的口子

**Comment by miaomiaojianglove** [comment]
> > 老哥能封装消息发送模块吗
> 
> 这是一个基础框架，封装消息发送是什么意思
就是现在目前不是只能收消息吗 比如我想给某个session发消息 或者给所有session广播怎么处理呢
原作者说要全部循环所有session才能发 但代码里面没有看到对应的口子

**Comment by twelvet-s** [comment]
> > > 老哥能封装消息发送模块吗
> > 
> > 
> > 这是一个基础框架，封装消息发送是什么意思
> > 就是现在目前不是只能收消息吗 比如我想给某个session发消息 或者给所有session广播怎么处理呢
> > 原作者说要全部循环所有session才能发 但代码里面没有看到对应的口子

这是业务问题，在链接客户端后自行处理NettySession的保存，比如hashmap，然后根据sessionid发送到指定NettySession

**Comment by twelvet-s** [comment]
> > > > 老哥能封装消息发送模块吗
> > > 
> > > 
> > > 这是一个基础框架，封装消息发送是什么意思
> > > 就是现在目前不是只能收消息吗 比如我想给某个session发消息 或者给所有session广播怎么处理呢
> > > 原作者说要全部循环所有session才能发 但代码里面没有看到对应的口子
> 
> 这是业务问题，在链接客户端后自行处理NettySession的保存，比如hashmap，然后根据sessionid发送到指定NettySession

可以参考这里：[IM](https://github.com/twelvet-projects/twelvet-mall/blob/master/twelvet-server/twelvet-server-im/src/main/java/com/twelvet/server/im/websocket/ChatWebSocket.java#L46)

**Comment by miaomiaojianglove** [comment]
> > > > > 老哥能封装消息发送模块吗
> > > > 
> > > > 
> > > > 这是一个基础框架，封装消息发送是什么意思
> > > > 就是现在目前不是只能收消息吗 比如我想给某个session发消息 或者给所有session广播怎么处理呢
> > > > 原作者说要全部循环所有session才能发 但代码里面没有看到对应的口子
> > 
> > 
> > 这是业务问题，在链接客户端后自行处理NettySession的保存，比如hashmap，然后根据sessionid发送到指定NettySession
> 
> 可以参考这里：[IM](https://github.com/twelvet-projects/twelvet-mall/blob/master/twelvet-server/twelvet-server-im/src/main/java/com/twelvet/server/im/websocket/ChatWebSocket.java#L46)
好的 感谢大佬 我明白了 感谢
